project:
  type: book
  output-dir: docs

book:
  title: "Notas de Aprendizaje y Comportamiento Adaptable"
  author: "Arturo Bouzas"
  repo-url: https://github.com/arbouria/Notas-Aprendizaje-y-Comportamiento-Adaptable-I
  date: "3/15/2025"
  repo-actions: [edit]
  sharing: [twitter, facebook]

  search:
    type: textbox
    location: sidebar
    copy-button: true
    limit: 10

  page-navigation: true

  sidebar:
    logo: cover.png
    pinned: false
    align: left
    style: floating
    collapse-level: 2
  
  page-footer:
      border: true 
      center: "Libro Apoyado por los Proyectos [PAPIME](https://dgapa.unam.mx/index.php/fortalecimiento-a-la-docencia/papime) PE309624 y PE302221"
      left:
        - text: "Acerca"
          href: index.qmd
      right: ''

  chapters:
      - index.qmd
      - Capítulo 1.qmd
      - Capítulo 2.qmd 
      - Capítulo 3.qmd
      - Capítulo 4.qmd
      - Capítulo 5.qmd
      - Capítulo 6.qmd
      - Capítulo 7.qmd
      - Capítulo 8.qmd
      - Capítulo 9.qmd
      - Capítulo 10.qmd
      - Capítulo 11.qmd
      - references.qmd
      
      
format:
    html:
      lang: es
      page-layout: full

      fig-format: png
      fig-responsive: true

      linestretch: 1.75
      fontsize: "18px"
      link-external-icon: false
      link-external-newwindow: true
      smooth-scroll: true
      number-sections: true
      toc: true
      toc-title: "Contenido"
      toc-depth: 3

      theme: 
          light: [cerulean, theme-light.scss]
          dark: [cerulean, theme-dark.scss]