---
title: "Principios de la Selección Natural"
format: html
---


## Arturo Bouzas

## “Nothing in Biology (Psychology) Makes Sense Except in the Light of Evolution”  Dobzhansky.

Como vimos en una nota anterior, la influencia de Darwin y el pensamiento seleccionista sobre la Psicología fue enorme. Hoy en día, para entender el comportamiento adaptado y adaptable, resulta indispensable conocer los principios más generales de la teoría de la selección natural. El propósito de esta nota es presentar estos principios. Para un tratamiento extenso del tema, revise las recomendaciones al final de la nota.

Para cualquier observador del mundo natural, dos propiedades le parecerán sorprendentes y merecedoras de contar con una explicación. La primera de ellas es la enorme variabilidad en morfología, fisiología y comportamiento de los organismos que habitan este planeta. La segunda, es que esta variabilidad parece estar finamente ajustada (adaptada) a las características del entorno que habitan los organismos.

#### 1. Variabilidad 
Un repaso de nuestra experiencia cotidiana, visitas a zoológicos y videos de historia natural en YouTube, nos alerta a la enorme variedad de organismos que pueblan nuestro planeta: desde organismos unicelulares, hongos, medusas, plantas de múltiples tamaños, insectos, peces, aves, mamíferos y desde luego humanos. La variabilidad no es solo a nivel de la morfología, se da también en los mecanismos fisiológicos y en el comportamiento de los seres vivos. Hay organismos que se desplazan, otros que no; organismos que se alimentan de un solo producto y otros que comen de todo; organismos que regulan su temperatura, otros que no; organismos que se reproducen sexualmente, otros que no; organismos que tienen una sola cría, otros que depositan cientos de huevos.  Aún entre una clase, como la de los perros, existen subtipos de todo tamaño, conformación, nivel de actividad, niveles de apego y agresividad. 

Actualmente se estiman entre 10 millones a un billón de especies. Solo entre mamíferos existen aproximadamente 5,500 especies, de insectos 91,000 y no deja de sorprender las 250,000 especies de escarabajos (buen tino de los “Beatles”). Solo en el intestino humano hay 140,000 especies virales, y se estiman entre un millón a 1 billón de especies de bacterias en nuestro planeta.  Bacterias y virus representan la mayoría de los organismos biológicos. 

La variabilidad observada cambia tanto a lo largo del espacio como a lo largo del tiempo. La variabilidad que registramos varía en sí misma dependiendo del lugar del planeta donde se lleve a cabo la observación. Lo que observamos en el desierto de Sonora es muy diferente a lo que observamos en la selva chiapaneca. Fue esta variabilidad lo primero que impactó a Darwin en su recorrido en el Beagle.

A mediados del siglo XIX, también se sabía que la variabilidad cambiaba a lo largo del tiempo. No solo había especies que ya habían desaparecido, sino, y esto era lo importante, ahora se sabía que también habían existido especies de las cuales no se tenían registros pero que habitaron la Tierra en etapas geológicas más tempranas. Era claro que el mundo biológico no había sido “creado” a un mismo tiempo y que podía hablarse de la evolución de los organismos. Gracias a los avances en la datación de capas geológicas, el análisis de fósiles nos permite determinar con mayor precisión la fecha de aparición de las diferentes especies. Estos datos confirman las predicciones de la teoría de Darwin sobre la evolución gradual y la ascendencia común. 

Ante el panorama descrito, surgen un número de  preguntas, ¿por qué no todos los organismos son iguales?, ¿cuál es el origen de esa gran variabilidad?, ¿cómo dar cuenta de ella y de su distribución en el espacio y en el tiempo? Fueron estas preguntas las que dieron origen a la noción de la evolución.

#### 2. Adaptación
Una segunda observación que requiere explicación, es el sorprendente ajuste (adaptación) de las características morfológicas, fisiológicas y de comportamiento , a las características del entorno donde se desenvuelve un organismo. No tan solo existe una inmensa variabilidad, sino que esta está correlacionada con las propiedades de entornos que varían espacial y temporalmente.  El ejemplo clásico de una adaptación morfológica lo observó Darwin al visitar los archipiélagos de las islas Galápagos y de Hawaii. Él encontró que la forma del pico de pequeños pájaros genéticamente relacionados, se ajustaba al tipo de alimento en la isla que habitaban. Cómo puede verse en la siguiente figura, el pico podía ser largo y delgado, apropiado para acceder al néctar dentro de una flor, o corto y fuerte para poder romper y comer semillas. 

### 3. Principios de la Selección Natural

Tres principios se encuentran atrás de la propuesta de Darwin para dar cuenta de la variabilidad y la adaptación de los rasgos de los individuos, en particular de los cambios en la  frecuencia relativa de los rasgos en una población :
 1. Variabilidad
Existe variabilidad en rasgos morfológicos, fisiológicos o conductuales entre miembros de una especie.
 2. La variabilidad es heredable
 3. Hay una covarianza entre los diferentes rasgos y el número de descendientes dejados por los individuos, la covarianza es parcialmente atribuible al papel causal de los rasgos. 
Si se satisfacen los tres principios que acabamos de describir, de generación a generación, el rasgo con mayor éxito reproductivo incrementará en frecuencia en la población. 

### 4. Determinantes del éxito reproductivo

#### 1. Filtros
Dada cierta variabilidad en un rasgo, la distribución estadística de las características del entorno es la que determina el éxito reproductivo diferencial de dicho rasgo. 
Una analogía útil para entender el proceso de selección natural es considerar a los entornos como filtros sobre la variabilidad en los rasgos. Son estos filtros los que cambian la frecuencia relativa de un rasgo en una población y determinan su éxito reproductivo diferencial.

Un ejemplo muy sencillo de selección es el juego infantil de inserción de cuerpos geométricos. La cubierta de la caja tiene un conjunto de orificios de diferentes formas: cuadrados, círculos y triángulos. La tarea para el infante es insertar en estos orificios a objetos con forma de cilindros, cubos o pirámides. Para hacer uso de esta analogía de la selección natural, imagine ahora una cubierta enorme de este tipo, con una distribución de orificios de las tres formas, y por otro lado, un saco con una población de los tres objetos con diferentes frecuencias relativas. Esa distribución de objetos sería el equivalente a la “generación número 1” dentro del esquema de la selección natural. Vaciamos el contenido del saco sobre la cubierta y observamos la distribución de objetos que quedaron después de pasar por el filtro de la misma. El número de objetos que sí se ajustaron a un lugar dentro de la cubierta es la distribución de objetos en la segunda generación. Esa distribución depende de dos factores: la distribución original -es decir,el número original de cubos, cilindros y pirámides- y de la distribución de los tres tipos de orificios en la cubierta. Si la cubierta solo tuviese cuadrados y círculos, en la segunda generación solo observaremos cilindros y cubos. Note que no se selecciona el mejor, solo se eliminan los que no pasan a través de los filtros. Un problema con el ejemplo anterior es que no contempla la creación de nuevos objetos. La selección natural necesita de un proceso que, de generación a generación, produzca nueva variabilidad.  

#### 2. Determinantes de la variabilidad

La variabilidad puede cambiar intrínsecamente, de generación en generación o puede cambiar por un factor externo que ocurre en una oportunidad. Dos factores están detrás del origen de la variabilidad de generación a generación.  El primero son las *mutaciones genéticas aleatorias*, el segundo es la *reproducción sexual*. El primero, las mutaciones genéticas aleatorias, produce modificaciones que pueden tener tres consecuencias: o bien ser letales para el individuo (haciendo que este no pase por ningún filtro evolutivo adicional); o inducir un mayor éxito reproductivo que los demás rasgos heredados (contribuyendo a que el individuo atraviese un nuevo filtro) o bien pueden ser neutrales y no tener ningún efecto sobre el éxito reproductivo. En este último caso, el gen mutado se desliza a lo largo de generaciones y cambia la frecuencia relativa de los diferentes genes: a este proceso se le conoce como *deriva genética* (vea el artículo de xxx para una descripción más detallada). La reproducción sexual es la segunda gran fuerza de variabilidad. La mitad de la conformación genética de cada descendiente proviene del macho y la otra mitad de la hembra; adicionalmente, cada una de las mitades proviene de  un muestreo aleatorio de los genes del macho y de la hembra.

La otra fuente de variabilidad es la que se genera cuando un accidente geológico aísla a una población o la divide en subpoblaciones que no pueden interactuar. Es el caso de una erupción volcánica, una separación geológica que forma una isla o algo creado por el humano, como una barda en medio del desierto. El *aislamiento geográfico* produce que un mismo acervo genético separado por una barrera geográfica pueda resultar, mediante la recombinación aleatoria, en dos poblaciones con rasgos diferentes. Dicho proceso inclusive puede derivar eventualmente en la generación de dos especies diferentes que ya no pueden reproducirse entre sí. 

#### En resumen, 
1. En la teoría de la selección natural los cambios en el éxito reproductivo diferencial se deben a las propiedades (filtros, restricciones) en el entorno de los organismos.   

2. La variabilidad aleatoria de los rasgos junto con los cambios en el entorno son el motor de la evolución y de la adaptación de los rasgos de un organismo. 

3. Como resultado de la operación de los tres principios de la selección natural, se observa un incremento gradual en el éxito reproductivo de ciertos rasgos en la población. Este incremento puede describirse como un proceso de ascenso de colina, que resulta en el ajuste de los rasgos a las propiedades estadísticas del entorno. 

4. Reservamos el término de *adaptación* a los rasgos resultado del proceso de selección natural. Es importante distinguir entre rasgos que son benéficos para un organismo en el presente de aquellos rasgos cuya existencia es el resultado de un proceso de selección natural.

5. Para entender la evolución de un rasgo, es necesario especificar en detalle los filtros, caracterizados como propiedades estadísticas del entorno. Entre los filtros más generales encontramos:
	a. Limitaciones en recursos
	b. Competencia con organismos de la misma especie y de otras especies 
	c. Selección sexual
	d. Selección dependiente de la frecuencia del rasgo

6. Una característica importante del proceso de selección natural es que con frecuencia actúa en entornos que son modificados por el mismo éxito reproductivo de una población. Adaptaciones a un nicho generan un nuevo nicho con un conjunto de nuevos filtros. 

7. La teoría de la selección natural debe acompañarse de la especificación de las restricciones, genéticas y físicas, que limitan el tamaño del espacio de los posibles rasgos que son candidatos viables para un proceso de selección. Por ejemplo, físicamente hay una relación posible entre el peso de un animal y el diámetro de sus patas. Es decir, ciertos tamaños de patas en algunas especies no son rasgos viables para ser seleccionados por selección natural debido a las restricciones físicas propias de la anatomía del organismo. En ese sentido, la selección natural no produce la solución perfecta a un problema, sino que resulta en la mejor de las posibles soluciones dado un conjunto de restricciones.

8. Encontramos dos tipos de explicaciones evolutivas:

	a. Explicaciones Causales: tras la observación de un rasgo y de su posible función, estas explicaciones buscan encontrar los cambios en los entornos, las posibles restricciones y la historia de esos rasgos que pueden dar cuenta de su aparición en una población.

	b. Explicaciones de optimización: estas explicaciones están ancladas en las herramientas de la teoría matemática de la optimización y consisten en elaborar modelos del entorno (preferentemente matemáticos) como un problema y derivar su solución óptima dado un conjunto de restricciones. El éxito de estas explicaciones se sustenta en la calidad del modelo de las propiedades estadísticas del entorno que funcionan como filtros y que constituyen el problema a resolver, así como de la identificación completa de las posibles restricciones de las cuales se derivan las soluciones.
	 
9. Sin embargo, no todos los rasgos observados son el resultado de un proceso de selección natural, hay otros factores que se combinan con el proceso de selección para poder entender la evolución de un rasgo. Estos factores están principalmente asociados con los procesos que resultan en la generación de variabilidad aleatoria. 
