---
title: "Evolución de la Adaptabilidad del Comportamiento: El papel de las restricciones"
author: "Arturo Bouzas"
format: html
---
Si el término “adaptación” se utiliza para designar aquellos rasgos que son resultado del proceso de selección natural, el concepto de “adaptabilidad” del comportamiento se define como la medida en que un comportamiento contribuye al éxito reproductivo en el presente. El primer término hace referencia al origen de un comportamiento, mientras que el segundo hace referencia a la función que cumple un comportamiento actualmente. En particular, la adaptabilidad de un comportamiento se modifica naturalmente en función de cómo este aporta a dos características clave de la vida de los organismos: el metabolismo y la reproducción (Godfrey-Smith, 2017). En cuanto al metabolismo, los sistemas biológicos gastan y agotan la energía almacenada y requieren de un constante abastecimiento de ella. Los procesos evolutivos van moldeando distintas formas exitosas de reabastecimiento a través del éxito reproductivo diferencial del organismo.

El reabastecimiento de energía a través de la acción del organismo está limitado por dos grupos de restricciones, uno del organismo y otro del entorno. La primera condición limitante es que el comportamiento toma un tiempo para llevarse a cabo. Dado que el tiempo disponible es ﬁníto, la suma de todos los comportamientos llevados a cabo es igual al total del tiempo disponible. 

$$
T = t_1 + t_2 + t_3 \dots t_n
$$

Esta es una *restricción lineal* bajo la cual los diferentes comportamientos *compiten* por el tiempo disponible. Este planteamiento asume que no existe tal cosa como una “ausencia de comportamiento”, por lo que en toda unidad de tiempo se está generando un tipo de conducta que consume una duración particular de tiempo (aunque este comportamiento sea “reposar” o que el organismo permanezca estático). Bajo este esquema, el incremento de una unidad de tiempo asignado a uno de los comportamientos por parte del organismo, implica una menor unidad de tiempo disponible para el resto de los comportamientos. Cada segundo de tiempo t dedicada al comportamiento 1 es una un segundo menos que puede dedicarse al resto de los *n* comportamientos.

Una segunda restricción del organismo es su estructura biológica metabólica y neuronal, las cuales limitan el posible rango de comportamientos y uso de recursos energéticos.  

El éxito reproductivo de un organismo no solo depende de su habilidad para reabastecerse de energía: es necesario, entre otras cosas, encontrar una pareja con la cual reproducirse, evitar depredadores y escapar del frío y/o calor extremo. Todas estas consecuencias tienen una importancia biológica por su impacto sobre el éxito reproductivo de los organismos y coinciden con lo que comúnmente se conoce como “refuerzos”: nosotros seguiremos a Baum y, para enfatizar el origen y el papel en la evolución de estos elementos, les llamaremos *sucesos biológicamente importantes SBI*. En la ecuación 1, corresponde a las acciones ligadas a los diferentes SBI. Cuando hablamos de SBI, no nos limitamos a lo que podría entenderse como necesidades básicas. Selección natural ha operado para filtrar mecanismos que permitan traducir éxito reproductivo diferencial en la detección de todas las variables que pueden estar correlacionadas con él. Por ejemplo, selección natural ha filtrado mecanismos de cognición social que permiten a diversos organismos detectar si una acción particular será bien recibida dentro de un grupo específico de su especie: si bien la aceptación social no se traduce inmediatamente en un mayor acceso a la reproducción o en mayores opciones para nutrir el metabolismo del organismo, a la larga la aceptación social es un SBI dado que facilita las condiciones que permiten al organismo un mayor acceso a ambos elementos. Por lo tanto, para diversas especies, la cognición social es un proxy del éxito reproductivo diferencial, aunque esta variable no satisface directamente una necesidad básica en términos evolutivos.

El segundo grupo de restricciones son aquellas que describen la disponibilidad de recursos de reabastecimiento y su relación a propiedades del entorno de los organismos. A estas restricciones les llamaremos las *propiedades estadísticas del entorno.* Son estás propiedades las que, en conjunción con la restricción lineal sobre el comportamiento, determinan el posible conjunto de distribuciones de acciones que han de ser sometidas al filtro de la selección natural. 

Las condiciones del entorno biológicamente importantes pueden ser relativamente constantes en el tiempo o variar a lo largo de él. Dependiendo de esa variabilidad en el entorno, el proceso de selección puede ocurrir en dos escalas temporales diferentes: puede darse entre generaciones o durante la vida individual de un organismo. Si las condiciones son constantes, el proceso de selección ocurre a lo largo de generaciones y resulta en programas conductuales específicos que en la Psicología se les ha conocido como reflejos, instintos o sesgos y de los cuales se dice que son el resultado de un proceso evolutivo. Podemos decir que el proceso evolutivo “codifica” genéticamente las condiciones constantes del ambiente. Consideren la tarea de diseñar un robot que se mueve en un entorno fijo y que tiene  solo una tarea por realizar. En ese caso, la solución del ingeniero consiste en *codificar* las características fijas del entorno en el software del robot. En el curso, vamos a llamar *comportamiento adaptado* al que resulta de un proceso de selección natural: es decir, el comportamiento resultante de un proceso de ajuste lento y gradual a las condiciones del entorno a lo largo de generaciones. En ese sentido, el comportamiento adaptado es un tipo de adaptación.

Sin embargo, los entornos de la mayoría de los organismos y de los robots de servicio y exploración espacial son entornos variables, volátiles e inciertos. Este tipo de entornos requieren de mecanismos que se ajusten a la variabilidad en tiempo real (y no a lo largo de generaciones) para poder ser afrontados con éxito. Por ejemplo, para diseñar un robot (como Wall-E) que pueda funcionar en entornos con SBI variables e inciertos, un ingeniero debe conocer y poder modelar la disponibilidad de fuentes de energía para el reabastecimiento del robot, la distribución de los SBI y la disponibilidad de opciones para que el agente pueda llevar a cabo su meta (que sería recolectar y compactar basura en el caso de Wall-E).

Los entornos variables, volátiles e inciertos se caracterizan por sus propiedades estadísticas. Sin esta variabilidad, no habría selección de mecanismos que permitan la adaptación de los organismos a entornos cambiantes dentro del periodo de sus vidas individuales. La adaptación del comportamiento de los organismos a las propiedades estadísticas del entorno dentro de su lapso de vida individual, la atribuimos a un proceso que llamamos “Aprendizaje”. 

En resumen, 

1. En entornos sin variabilidad, la selección natural puede resultar en comportamientos adaptados a las propiedades invariantes del entorno.

2. En entornos variables e inciertos, selección natural resulta en el
surgimiento de mecanismos que permiten “comportamiento adaptable” y que llamaremos *aprendizaje* (¡ojo! este concepto es distinto al de “comportamiento adaptado”).

1. Selección natural opera en estructuras, genes y las expresiones de genes (como un sistema nervioso, por ejemplo). Estos son los elementos que permiten y subyacen a los mecanismos del comportamiento adaptable.

En términos evolutivos, la tarea de los agentes es *reducir la incertidumbre* acerca de la ocurrencia de los SBI, *predecir* efectivamente su ocurrencia y llevar a cabo las *acciones* necesarias para interactuar óptimamente con estos. Así, un primer paso para el estudio del comportamiento inteligente es tener una especificación detallada de las propiedades estadísticas de los entornos de los organismos. Cuatro propiedades estadísticas de los sucesos biológicamente importantes han dominado el estudio del comportamiento adaptable: el tiempo y el lugar de ocurrencia, la relación (correlación, covarianza) con otras características del entorno y la relación con el comportamiento de un organismo. El supuesto más importante que haremos es que si las consecuencias relevantes en el entorno se distribuyen en ciertos tiempos, lugares y están asociadas con ciertas estímulos y comportamientos, un organismo que pueda detectar estas propiedades estadísticas y ajustar su conducta a ellas, podrá asignar más óptimamente su distribución de comportamiento a las metas en competencia. 

Los SBI ocurren de forma incierta y la tarea para los organismos es descubrir si su ocurrencia está ligada a ciertos tiempos o a ciertos lugares. Pueden también  formar parte de una estructura causal, y en esos casos, la tarea de los organismos es descubrir con qué propiedades del entorno están vinculados. Adicionalmente, los SBI pueden depender de las acciones de los agentes, en cuyo caso, la tarea es descubrir cuál acción es responsable de su ocurrencia.

Una propiedad adicional de los entornos es que las cuatro posibles regularidades que acabamos de detallar (características estadísticas del entorno), pueden variar a su vez de acuerdo a otros estados externos del mundo de los agentes (noche y día, escuela y casa). En los libros de texto, a la adaptación de los organismos ante estas propiedades del contexto se les estudia bajo el nombre de control de estímulos.

Un problema de adaptación más difícil es cuando las propiedades estadísticas del entorno cambian sin señales externas, como resultado de estados ocultos al agente. En estos casos, la tarea es determinar si el cambio observado en la propiedad estadística del entorno constituye un cambio aleatorio o si realmente se trata de una modificación en el estado particular del mundo. En la literatura clásica, a este problema se le ha estudiado bajo el nombre del fenómeno de la extinción. 

Hasta el momento hemos supuesto, al igual que la gran mayoría de los teóricos hasta los años 60s del siglo pasado, que los organismos solo detectan sucesos individuales. Revisaremos evidencia de que en adición, los organismos detectan y se adaptan a una característica de segundo orden de los entornos: la tasa de ocurrencia de sucesos individuales en su entorno, la cual se define como el número  de sucesos por unidad de tiempo. Por ejemplo, las abejas seleccionan su tiempo de estancia en diferentes lugares de un jardín en función de la tasa de encuentro con flores con néctar. Veremos que la noción de tasa de ocurrencia juega un papel muy importante en las explicaciones contemporáneas del comportamiento. 

 Finalmente, podemos considerar una propiedad de los entornos que puede considerarse de tercer nivel. Nos referimos a la incertidumbre acerca
del tiempo, lugar, covarianzas y tasas de los SBI. Los camiones de transporte público no pasan siempre a la misma hora (incertidumbre de tiempo), en el mercado no siempre se encuentra la misma fruta (incertidumbre de lugar), no llueve siempre que está nublado (incertidumbre de covarianzas) y un jugador de fútbol no alcanza siempre la misma tasa de goleo en una temporada (incertidumbre de tasas). Hay una relación que podemos describir como una probabilidad condicional en el sentido de que la probabilidad de un evento en sí misma depende (o se encuentra condicionada) a otra distribución de probabilidad. Esta descripción nos sirve para distinguir entre cuando la incertidumbre de un evento es esperada o inesperada. La incertidumbre es esperada si existe una única distribución de probabilidad que la describa. Es el caso cuando se lanza una moneda sin imperfecciones al aire, donde sabemos que la probabilidad de que caiga águila o sol es de 0.5. Por otro lado, la incertidumbre es inesperada cuando los parámetros de la distribución cambian de acuerdo a una segunda distribución de probabilidad: en este caso se habla de una probabilidad condicional. Un caso sería una moneda cuya probabilidad de que caiga águila cambia a lo largo del tiempo de acuerdo a otra probabilidad, como la distribución de la velocidad del viento en un entorno, por ejemplo. 

En conclusión, si asumimos que la teoría de la selección natural es una descripción correcta y si los organismos y el entorno operan bajo las restricciones descritas, podemos concluir que el objeto de estudio natural de la Psicología es el estudio de la adaptabilidad del comportamiento. En otras palabras, la Psicología estudia distintos comportamientos y los explica en función de su capacidad para brindarle acceso al organismo a sucesos que le son biológicamente significativos. 

En el curso veremos cuales son las soluciones óptimas a los diferentes problemas de adaptación generales que encaran los organismos, así como los distintos mecanismos que posibilitan alcanzar tales soluciones a distintas especies. Veremos que para lograr el objetivo de entender el comportamiento adaptable es fructífero iniciar con un detallado análisis del problema de adaptación en cuestión. Esto último requiere modelar tanto las propiedades estadísticas del problema como las restricciones que imponen los posibles mecanismos de las distintas especies sobre la solución óptima.


